name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [17]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java-version }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Unit Tests with Surefire
        run: mvn test

      - name: Run Integration Tests with Failsafe
        run: mvn verify

      - name: Publish Surefire HTML Reports as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: surefire-html-reports
          path: target/site/surefire-report.html
      
      - name: Publish Failsafe HTML Reports as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: failsafe-html-reports
          path: target/site/failsafe-report.html

      - name: Publish Failsafe Test Reports as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: failsafe-reports
          path: target/site/failsafe-reports
          
      - name: List report files
        run: ls -alh target/site/

      - name: Build Docker Image
        run: |
          docker build -t dingwei426/oh-core_database:latest -f Dockerfile-ohdb .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to DockerHub
        run: docker push dingwei426/oh-core_database:latest